language: node_js
sudo: false
node_js:
- '4'
- '6'
script:
- npm run ci
after_script:
- npm install -g codeclimate-test-reporter
- npm run cover
- codeclimate-test-reporter < coverage/lcov.info
notifications:
  email: false
  slack:
    secure: JMUlNkD8pEFEco9mXx0jYqJC1ArO41e8bBIBStpu9fkta4/Vh8COgtvonP7yHvX4rFUfJmLIptGyYY+j82u+6ehP8hU9JpueZtg8vhttpdYJ51wEdbNzCR6VeokBg0Sy48bWEx6xdYhA7DjwvnG1nO8xxf3eFaQZP012Ad7dB1lmPvg4rT4un0z1/ylRBfOg+wqmDJVPqIXcF/mne6w61DAhVUw5j7htnNbZEEvzlUPPX8cqZJriCgrNy3iBFTCf/YIeDq3D5yF2j8Zo4jsLS/Yi26WFVjDTp82ptswrlwYguEQJIWIn3rwoW3RREFxwG+/nWFmRpuGXKKnd4qcGPA+G1gSGDm7upPbwgbRTIWlcXw/NJRw0fMRDTafpU+EedZ1Hzqfiuh80DEJRQst53UeELOMDHhlpSg3x1FKI7HRcY+HDwvqWMfcAwMRfpej1+neqf7SWsDNlozUPh1f9v6+hBnMpOidtcQnfpruJo4z14kiJk2Ejz8lrYfOzYDzfURQ8dnFv4+cZPZwZvzPYYKS9rsHCRUTV66i+5lCmjpbk/ugeVyPqZ8esep3VtRjnk/M4hswDex92JM6n5voN88vmrizyxhmGtqy+OYDGO4iPOHJtHzHWRugSCtSLC2ujx6n//Q3gaI36+ju2uXyez40QDSCK5jZJtUA6BY4j9qg=
